Work session show
Crysicia/Tea-Wall pull request #20
Opened 2019-02-21 18:13 UTC by orohellec

liste d'appel opérationnel ok !

2019-02-21 18:14 UTC, orohellec commented
Attendez j'ai oublié de supprimer certaines lignes qui ne sont pas utiles.

2019-02-21 18:21 UTC, orohellec commented
> Attendez j'ai oublié de supprimer certaines lignes qui ne sont pas utiles.

C'est bon maintenant !

2019-02-21 19:25 UTC, Crysicia requested changes

2019-02-21 19:25 UTC, Crysicia commented on app/controllers/work_sessions_controller.rb
> +    @work_session = WorkSession.find(params[:id])
You should make use of `find_work_session`

2019-02-21 19:25 UTC, Crysicia commented on db/migrate/20190221115122_add_field_present_to_work_session_students.rb
> +    add_column :work_session_students, :present, :boolean, default: 0
It's a boolean, so the default should be either `true` or `false`

2019-02-22 09:29 UTC, Crysicia approved these changes

2019-02-22 09:34 UTC, merged